### ISSUE TITLE
Copyright Violation

### ISSUE THREAD

**Issue by kyranet** [dikkemeuk/discordbot1#1]
Cheers!

I am contacting you because you have a lot of code from my old bot, Sneyra, and you did not comply with the MIT license my project has. In particular, the offending files are the following:

https://github.com/dikkemeuk/discordbot1/blob/dd67f2b22666d038042587c9d37119b0feab7b03/lib/structures/MusicManager.js
https://github.com/dikkemeuk/discordbot1/blob/dd67f2b22666d038042587c9d37119b0feab7b03/lib/structures/MusicCommand.js

Adding a banner such as the following:

```javascript
// MIT License | Copyright (c) 2017-2018 Kyra
// https://github.com/kyranet/Sneyra
```

Would solve the condition required by the license to distribute, you can view the license [here](https://github.com/kyranet/Sneyra/blob/master/LICENSE).

I hope to hear from you soon 👍

**Comment by dikkemeuk** [comment]
Added credits, my apologies

**Comment by kyranet** [comment]
No problem! I was browsing around some repositories and found that. Thank you for your fast response ^-^
